- name: Gather facts for everyone
  hosts: localhost
  gather_facts: true
  tasks:
    - debug: msg="at least one task required for play to gather facts"

- name: The next play, does not gather facts
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Show that we still know the facts
    ansible.builtin.debug:
      var: ansible_facts
