---
- name: Deploy HTTPS websites
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install software
      dnf:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: latest

    - name: Configure Apache for HTTPS
      copy:
        src: files/ssl.conf
        dest: /etc/httpd/conf.d/ssl.conf
      notify: restart_apache

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Allow services through the firewall
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - http
        - https

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted

