---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    var1: "test1"
    var2: "test2"
    var3: "{{var1}}"
  tasks:
    - debug: var=var3
    - set_fact:
        var3: "{{var2}}"
    - debug: var=var3
